### ISSUE TITLE
Trouble running CLI

### ISSUE THREAD

**Issue by Marantz2600** [zaproxy/zest#142]
I downloaded the source code and built it according to the instructions.

But there is no "zest.sh" as referenced in the wiki. So I just try to run it from the command line.

Probably because I am an idiot about Java, it does not work. I suppose that I need a classpath or something. Anyway someone could help me? I am on Debian Testing.

----> pwd
/home/sls/work/src/zest

----> find -iname zest.sh

----> java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

----> java -jar build/libs/mozilla-zest-0.14-SNAPSHOT.jar 
Usage: -script <file> [-summary | -list] [-debug] [-prefix <http://prefix>] [-token <name>=<value>]...
    [-http-auth-site <site> -http-auth-realm <realm> -http-auth-user <user> -http-auth-password <password>] 
    For more information about Zest visit https://developer.mozilla.org/en-US/docs/Zest

----> java -jar build/libs/mozilla-zest-0.14-SNAPSHOT.jar -script ~/.ZAP/scripts/scripts/standalone/main-xsgy-page-login-logout.zst -list
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/JsonDeserializer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.mozilla.zest.impl.CmdLine.main(CmdLine.java:144)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonDeserializer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

**Comment by psiinon** [comment]
Ah, looks like the wiki is out of date then - we'll need to change that :)
If you follow the instructions here https://github.com/mozilla/zest#building then you should get a set of files created in the build/distributions directory.
Expand one of them, eg mozilla-zest-0.13.zip and cd into the mozilla-zest-0.13 directory.
Then you can just run bin/mozilla-zest (or bin/mozilla-zest.bat on windows):

> $ bin/mozilla-zest
> Usage: -script <file> [-summary | -list] [-debug] [-prefix <http://prefix>] [-token <name>=<value>]...
>     [-http-auth-site <site> -http-auth-realm <realm> -http-auth-user <user> -http-auth-password <password>] 
>     For more information about Zest visit https://developer.mozilla.org/en-US/docs/Zest
> 

```

**Comment by Marantz2600** [comment]
Ok. That makes sense. I will try that. Thanks very much for the quick
response.

**Comment by thc202** [comment]
Wiki page updated.
